{% set name = "r-grumps" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

source:
  url: https://raw.githubusercontent.com/kalebabram/r-grumps/main/LICENSE
  fn: LICENSE

requirements:
  build:
    - wget
    - r-essentials 
    - r-devtools
    - r-ape
    - r-optparse 
  run:
    - r-essentials 
    - r-ape
    - r-optparse
test:
  commands:
    - r-grumps --help

about:
  summary: Genomic distance based Rapid Uncovering of Microbial Population Structures
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  license_url: https://github.com/kalebabram/r-grumps/blob/main/LICENSE

extra:
  recipe-maintainers:
    - kalebabram
