name: grumps
channels:
  - conda-forge
  - kabram

dependencies:
  - python
  - networkx
  - pandas
  - scipy
  - numpy
  - seaborn
  - scikit-learn
  - r-essentials=3.6.0
  - r-devtools
  - r-optparse
  - r-sparcl
  - py-grumps
  - r-grumps
