{% set name = "grumps" %}
{% set version = "0.9.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0c3b1530ed2cf32f2fcbdcec62d7aff3a4ced4671ccf2c3bc58a149f45edf71


build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

package:
  name: {{ name|lower }}
  version: {{ version }}

requirements:
  build:
    - python >=3.7
    - wget
    - hatchling
    - pip
    - r-essentials 
    - r-devtools
    - r-ape
    - r-optparse 
  run:
    - python 
    - scikit-learn
    - scipy
    - seaborn 
    - pandas 
    - numpy 
    - networkx 
    - r-essentials 
    - r-ape
    - r-optparse
test:
  imports:
    - grumps
  commands:
    - grumps --help
    - distmat_converter --help
    - r-grumps -h 

about:
  summary: Genomic distance based Rapid Uncovering of Microbial Population Structures
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kalebabram
